### PR TITLE
fix: use native performance object in Node 18

### LINKED ISSUE #17: Add support for Node.js Performance Timing API
Node.js `8.5.0` includes [`performance.measure()`](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_measure_name_startmark_endmark), [`performance.mark()`](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_mark_name), [`performance.clearMarks()`](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_clearmarks_name) and [`performanceObserverEntryList.getEntries()`](https://nodejs.org/api/perf_hooks.html#perf_hooks_performanceobserverentrylist_getentries).

Adding support would be nice. Thanks for this library!

### PR DESCRIPTION
**Pull request by nolanlawson**
Fixes #17

### CODE REVIEW

**Comment by nolanlawson** [comment]
The fix we want to detect in Node is this one: https://github.com/nodejs/node/pull/42032

But it's not observable, so we detect this slightly later fix: https://github.com/nodejs/node/pull/42725

This is probably good enough for marky. There's no huge advantage right now (AFAICT) of using Node's built-in performance timeline, but hey, maybe someday they'll have a great debugger or something that takes advantage of native marks/measures.

File: src/index.js [hunk 1]
```diff
@@ -31,9 +31,19 @@ let clear
 if (
   perf &&
   perf.mark &&
+  perf.measure &&
   perf.getEntriesByName &&
   perf.getEntriesByType &&
-  perf.clearMeasures
+  perf.clearMarks &&
+  perf.clearMeasures &&
```
Comment (nolanlawson) [inline src/index.js:38]: Seems prudent to check for every API we might use, and not rely on `measure` existing if `mark` exists, and `clearMarks` existing if `clearMeasures` exists.

File: src/now.js [hunk 2]
```diff
@@ -11,9 +11,9 @@ if (!process.browser) {
...
-  nowForNode = () => ((getNanoSeconds() - loadTime) / 1e6)
+  nowPolyfillForNode = () => ((getNanoSeconds() - loadTime) / 1e6)
 }
 
-export default process.browser
-  ? perf && perf.now ? () => perf.now() : () => Date.now()
-  : nowForNode
+export default perf && perf.now
+  ? () => perf.now()
+  : process.browser ? () => Date.now() : nowPolyfillForNode
```
Comment (nolanlawson) [inline src/now.js:19]: Could probably get a microsecond perf boost from doing `const now = perf.now.bind(perf)`, but meh. I don't want to rely on `bind`, or on `now()` working without the proper `this`, etc.
