### PR TITLE
fix: support node 16, feature detect performance API

### LINKED ISSUE #18: Does not work in node 16, `TypeError: perf.getEntriesByName is not a function`
In node 16, `performance` is a global with the `mark` method (so the hrtime path isn't used), but it does not have `getEntriesByName` (so marky.stop throws an exception). Feature detection is now necessary for all the performance methods used :/

https://github.com/nolanlawson/marky/blob/9e43c8ee7c94931b5fc25880b0ef2bad80959daa/src/index.js#L31

Originally surfaced in https://github.com/GoogleChrome/lighthouse-ci/issues/596

### PR DESCRIPTION
**Pull request by patrickhulce**
fixes #18 or at least one possible solution :)

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -28,7 +28,13 @@ let stop
 let getEntries
 let clear
 
-if (perf && perf.mark) {
+if (
+  perf &&
+  perf.mark &&
+  perf.getEntriesByName &&
```
Comment (mojavelinux) [inline src/index.js:34]: It's probably enough to stop after getEntriesByName. See https://developer.mozilla.org/en-US/docs/Web/API/Performance vs https://nodejs.org/api/perf_hooks.html

Another solution is to higher up and not try to bind to the performance global if the environment is Node.

Comment (patrickhulce) [reply src/index.js:34]: > It's probably enough to stop after getEntriesByName. See https://developer.mozilla.org/en-US/docs/Web/API/Performance vs https://nodejs.org/api/perf_hooks.html

It's enough *right now* ;)

> Another solution is to higher up and not try to bind to the performance global if the environment is Node.

Sure, I don't have a preference for how @nolanlawson would like to have it fixed so long as it is fixed :)

Comment (mojavelinux) [reply src/index.js:34]: > It's enough right now ;)

It's a stable API on both sides, so there's no good reason it would change. But I can't say that checking for every method is wrong, either ;)

Comment (nolanlawson) [reply src/index.js:34]: I'm fine with checking for every single method. This ensure that some version of Node in the future or some other JS environment doesn't have a similar error. :)

**Comment by nolanlawson** [comment]
Thanks a lot!

**Comment by nolanlawson** [comment]
Released in marky v1.2.2

**Comment by patrickhulce** [comment]
Hurray! Thanks for the swift action and release here @nolanlawson :)
